version: '3.0'

services:
  # первый сервис - NGINX
  nginx: 
    image: nginx
    # зависит от сервиса - php
    depends_on:
      - php
    # тут мы маппим дефолтный конфиг файл и папку с версткой
    volumes:
      - ./docker/default.nginx:/etc/nginx/conf.d/default.conf
      - ./app/:/var/www/html/
    container_name: lab_1_nginx
  php:
    # php сервис мы собираем из нашего образа, для этого указываем путь до Dockerfile
    # в нашем случае - docker/php/Dockerfile
    build:
      context: ./docker/php
    container_name: lab_1_php
    # так же маппим конфиг файл и папку проекта
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./html/:/var/www/html/

  db:
    image: mysql:5.7
    container_name: lab_1_phpdb
    # директива, которая позволяет запускать команды при запуске контейнера
    command: --default-authentication-plugin=mysql_native_password
    # открываем порты (не обязатально делать, я сделал чтобы приконектиться с помощью клиента)
    ports:
        - "3306:3306"
    volumes:
      - ./docker/mysql_data/:/var/lib/mysql
    # переменные окружения
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    container_name: lab_1_phpma
    # открываем внешний порт для того, чтобы открыть phpmyadmin
    ports: 
          - "8108:80"